project/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as auth_views

from posts.views import Index, Profile, PostPost, Search, SearchTag, TagJson


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', Index.as_view(), name='index'),
    #http://127.0.0.1:8000/user/<username>,
    url(r'^user/(\w+)/$', Profile.as_view()),
    url(r'^user/(\w+)/post/$', PostPost.as_view()),
    # url: 127.0.0.1:8000/search/?q=<q>
    url(r'^search/$', Search.as_view()),
    url(r'^search/hashtag$', SearchTag.as_view()),
    url(r'^hashtag.json$', TagJson.as_view()),
    url(r'^login/$', auth_views.login),
    url(r'^logout/$', auth_views.logout),


]

posts/models.py
from django.db import models
from user_profile.models import User

class Post(models.Model):
    ''' Post model '''
    user = models.ForeignKey(User)
    text = models.CharField(max_length = 300)
    created_date = models.DateTimeField(auto_now_add=True)
    location = models.CharField(max_length=30, default='Global')
    is_active = models.BooleanField(default = True)
    is_favorite = models.BooleanField(default = False)

    def __str__(self):
        return self.text[:50]


class HashTag(models.Model):
    ''' HashTag model '''
    name = models.CharField(max_length = 100, unique = True)
    post = models.ManyToManyField(Post)

    def __str__(self):
        return self.name

user_profile/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractBaseUser

class User(AbstractBaseUser):
    username = models.CharField('username', max_length = 20, unique = True, db_index = True)
    email = models.EmailField('email address', unique = True)
    joined = models.DateTimeField(auto_now_add = True)
    is_active = models.BooleanField(default = True)
    is_admin = models.BooleanField(default = False)

    USERNAME_FIELD = 'username'

    def __str__(self):
        return self.username

posts/forms.py
from django import forms

class PostForm(forms.Form):
    text = forms.CharField(widget=forms.Textarea(attrs={
        'rows': 3,
        # 'cols': 80,
        'class' : 'form-control',
        'placeholder' : 'Write your post here'
    }), max_length = 300)

class SearchForm(forms.Form):
    q = forms.CharField(widget=forms.TextInput(attrs={
        'size' : 30,
        'class' : 'form-control search-query',
        'autofocus': 'autofocus',
        'placeholder' : 'text'
    }))

class SearchTagForm(forms.Form):
    q = forms.CharField(widget=forms.TextInput(attrs={
        'size' : 30,
        'class' : 'form-control search-tag-query typeahead',
        'id' : 'typeahead',
        'autofocus' : 'autofocus',
        'placeholder': 'start typing...'
    }))

posts/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.template.loader import render_to_string
import json

# Create your views here.
from django.http import HttpResponse
from django.views import View
from .models import Post, HashTag
from user_profile.models import User
from posts.forms import PostForm, SearchForm, SearchTagForm

class Index(View):

    def get(self, request):
        context = {'text': 'Hello, world!'}
        print(context)
        return render(request, 'base.html', context)

class Profile(View):
    """ User Profile Page url: 127.0.0.1:8000/user/<username> """

    def get(self, request, username):
        user = User.objects.get(username=username)
        posts = Post.objects.filter(user=user)
        form = PostForm()
        context = {
            'posts' : posts,
            'user' : user,
            'form' : form,
        }
        return render(request, 'profile.html', context)

class PostPost(View):
    """Create Post View"""
    def post(self, request, username):
        form = PostForm(self.request.POST)
        if form.is_valid():
            user = User.objects.get(username=username)
            post = Post(text = form.cleaned_data['text'], user = user)
            post.save()
            words = form.cleaned_data['text'].split(" ")
            for word in words:
                if word.startswith('#'):
                    hash_tag, created = HashTag.objects.get_or_create(name=word)
                    hash_tag.post.add(post)
        return HttpResponseRedirect('/user/'+username)

class Search(View):
    """ Search all posts url: 127.0.0.1:8000/search/?q=<q>"""

    def get(self, request):
        form = SearchForm()
        context = {'search' : form}
        return render(request, 'search.html', context)

    def post(self, request):
        form = SearchForm(request.POST)
        if form.is_valid():
            q = form.cleaned_data['q']
            posts = Post.objects.filter(text__icontains=q)
            context = {'q' : q, 'posts' : posts}
            return_str = render_to_string ('part_views/_post_search.html', context)
            return HttpResponse(json.dumps(return_str), content_type='application/json')
        else:
            HttpResponseRedirect("/search/")

class SearchTag(View):
    """ Search tags with autocomplete (live search) """

    def get(self, request):
        form = SearchTagForm()
        context = {'searchtag' : form}
        return render(request, 'search_tags.html', context)

    def post(self,request):
        q = request.POST['q']
        form = SearchTagForm()
        tags = HashTag.objects.filter(name__icontains=q)
        context = {'tags' : tags, 'searchtag' : form}
        return render(request, 'search_tags.html', context)

class TagJson(View):
    """ Search tags with autocomplete (live search) json data"""
    def get(self, request):
        q = request.GET.get('q', '')
        taglist = []
        tags = HashTag.objects.filter(name__icontains=q)
        for tag in tags:
            new = {'q' : tag.name, 'count' : int(len(tag.post.all()))}
            taglist.append(new)
        return HttpResponse(json.dumps(taglist), content_type="application/json")

user_profile/views.py
from django.shortcuts import render

# Create your views here.

posts/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Test</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/project.css' %}">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
      {% block css %}
      {% endblock %}
  </head>
  <body>

  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <a href="#" class="navbar-brand">My Posts</a>
          {% block navbar %}
          {% endblock %}
      </div>

  </nav>

  <div class="container">
    {% block content %}

    {% endblock %}
  </div>


    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
  {% block js %}
  {% endblock %}
  </body>
</html>

posts/templates/part_views/_post_search.html
<div class="col-md-12 column">

    {% for post in posts %}

        <div class="well">
            {{ post.text }}
            <p></p>
            <p>
              <i class="icon-user"></i><a href="/user/{{ post.user }}">{{ post.user }}</a>
              | {{ post.created_date | date:"d/m/Y"}}
              | <a href="#"><i class="glyphicon glyphicon-comment"></i> Comments</a>
              | <a href="#"><i class="glyphicon glyphicon-share-alt"></i> Shares</a>
                {% if post.hashtag_set.all|length > 0 %}
              | <i class="icon-tags"></i> Tags:
                {% for hashtag in post.hashtag_set.all %}
                <a href="#"><span class="label label-info">{{ hashtag }}</span></a>
                {% endfor %}
                {% endif %}
            </p>
        </div>

    {% endfor %}

    {% if not posts %}
        <h3> No posts for this query.</h3>
    {% endif %}

</div>

posts/templates/profile.html
{% extends 'base.html' %}

{% block navbar %}
    <p class="navbar-text navbar-left">
        <i class="glyphicon glyphicon-user"></i> profile.username {{ profile.username }}
    </p>

    <p class="navbar-text navbar-right">
        <a href="/user/{{ user.username }}"><i class="glyphicon glyphicon-user"></i>{{ user.username }}</a>
    </p>
{% endblock %}

{% block content %}

<div class="row clearfix">

    <div class="col-md-12 column">

        <form action="post/" method="post">
            {% csrf_token %}
            <div class="col-md-8 col-md-offset-2 fieldWrapper form-group">
                {{ form.text.errors }}
                {{ form.text }}
            </div>
            <button type="submit" class="btn btn-primary"><i class=""></i>Post</button>
        </form>

    </div>

    <div class="col-md-12 column">

        {% for post in posts %}

            <div class="well">
                {{ post.text }}
                <p></p>
                <p>
                  <i class="icon-user"></i><a href="/user/{{ user.username }}">{{ user }}</a>
                  | {{ post.created_date | date:"d/m/Y"}}
                  | <a href="#"><i class="glyphicon glyphicon-comment"></i> Comments</a>
                  | <a href="#"><i class="glyphicon glyphicon-share-alt"></i> Shares</a>
                    {% if post.hashtag_set.all|length > 0 %}
                  | <i class="icon-tags"></i> Tags:
                    {% for hashtag in post.hashtag_set.all %}
                    <a href="#"><span class="label label-info">{{ hashtag }}</span></a>
                    {% endfor %}
                    {% endif %}
                </p>
            </div>

        {% endfor %}

    </div>

</div>

{% endblock %}

posts/templates/search.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
    <div class="row clearfix">
        <div class="col-md-6 col-md-offset-3 column" style="padding-bottom: 20px;">
            <form action="" method="post" id="search-form">
                {% csrf_token %}
                <div class="input-group input-group-sm">
                    {{ search.q.errors }}
                    {{ search.q }}
                    <span class="input-group-btn">
                        <button class="btn btn-search" type="submit">search</button>
                    </span>
                </div>
            </form>
        </div>

    </div>
    <div class="row clearfix">
        <div class="col-md-12 column posts">
        </div>
    </div>






{% endblock %}

{% block js %}
    <script src="{% static 'js/search.js' %}"></script>
{% endblock %}

posts/templates/search_tags.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/tag_suggestion.css' %}">
{% endblock %}

{% block content %}
    <div class="row clearfix">
        <div class="col-md-6 col-md-offset-3 column" style="">
            <form action="" method="post" id="search-form" autocomplete="off">
                {% csrf_token %}
                <div class="input-group input-group-sm">
                    <div class="tag-suggestion">
                    {{ searchtag.q.errors }}
                    {{ searchtag.q }}
                    </div>

                    <span class="input-group-btn">
                        <button class="btn btn-search" type="submit">search</button>
                    </span>
                </div>
            </form>
        </div>

    </div>


    <div class="row clearfix">
        <div class="col-md-12 column posts">
            {% for tag in tags %}
                {% for post in tag.post.all %}
                    <div class="well">
                        {{ post.text }}
                        <p></p>
                        <p>
                          <i class="icon-user"></i><a href="/user/{{ post.user }}">{{ post.user }}</a>
                          | {{ post.created_date | date:"d/m/Y"}}
                          | <a href="#"><i class="glyphicon glyphicon-comment"></i> Comments</a>
                          | <a href="#"><i class="glyphicon glyphicon-share-alt"></i> Shares</a>
                            {% if post.hashtag_set.all|length > 0 %}
                          | <i class="icon-tags"></i> Tags:
                            {% for hashtag in post.hashtag_set.all %}
                            <a href="#"><span class="label label-info">{{ hashtag }}</span></a>
                            {% endfor %}
                            {% endif %}
                        </p>
                    </div>
                {% endfor %}
            {% endfor %}

        </div>
    </div>


{% endblock %}

{% block js %}
    <script src="{% static 'js/typahead.js' %}"></script>
    <script src="{% static 'js/search_tag.js' %}"></script>

{% endblock %}